const jsonfile = require('jsonfile')

const integrations = {
    'adroll': '@saaskit/adroll',
    'adwords': '@saaskit/adwords',
    'alexa': '@saaskit/alexa',
    'amplitude': '@saaskit/amplitude',
    'appcues': '@saaskit/appcues',
    'atatus': '@saaskit/atatus',
    'autosend': '@saaskit/autosend',
    'awesm': '@saaskit/awesm',
    'bing-ads': '@saaskit/bing-ads',
    'blueshift': '@saaskit/blueshift',
    'bronto': '@saaskit/bronto',
    'bugherd': '@saaskit/bugherd',
    'bugsnag': '@saaskit/bugsnag',
    'chameleon': '@saaskit/chameleon',
    'chartbeat': '@saaskit/chartbeat',
    'clicktale': '@saaskit/clicktale',
    'clicky': '@saaskit/clicky',
    'comscore': '@saaskit/comscore',
    'crazy-egg': '@saaskit/crazy-egg',
    'curebit': '@saaskit/curebit',
    'customerio': '@saaskit/customerio',
    'drip': '@saaskit/drip',
    'elevio': '@saaskit/elevio',
    'errorception': '@saaskit/errorception',
    'evergage': '@saaskit/evergage',
    'extole': '@saaskit/extole',
    'facebook-conversion-tracking': '@saaskit/facebook-conversion-tracking',
    'facebook-custom-audiences': '@saaskit/facebook-custom-audiences',
    'foxmetrics': '@saaskit/foxmetrics',
    'frontleaf': '@saaskit/frontleaf',
    'fullstory': '@saaskit/fullstory',
    'gauges': '@saaskit/gauges',
    'get-satisfaction': '@saaskit/get-satisfaction',
    'google-analytics': '@saaskit/google-analytics',
    'google-tag-manager': '@saaskit/google-tag-manager',
    'gosquared': '@saaskit/gosquared',
    'heap': '@saaskit/heap',
    'hellobar': '@saaskit/hellobar',
    'hittail': '@saaskit/hittail',
    'hubspot': '@saaskit/hubspot',
    'improvely': '@saaskit/improvely',
    'insidevault': '@saaskit/insidevault',
    'inspectlet': '@saaskit/inspectlet',
    'intercom': '@saaskit/intercom',
    'keen-io': '@saaskit/keen-io',
    'kenshoo': '@saaskit/kenshoo',
    'kissmetrics': '@saaskit/kissmetrics',
    'klaviyo': '@saaskit/klaviyo',
    'livechat': '@saaskit/livechat',
    'lucky-orange': '@saaskit/lucky-orange',
    'lytics': '@saaskit/lytics',
    'mixpanel': '@saaskit/mixpanel',
    'mojn': '@saaskit/mojn',
    'mouseflow': '@saaskit/mouseflow',
    'mousestats': '@saaskit/mousestats',
    'navilytics': '@saaskit/navilytics',
    'nudgespot': '@saaskit/nudgespot',
    'olark': '@saaskit/olark',
    'optimizely': '@saaskit/optimizely',
    'outbound': '@saaskit/outbound',
    'perfect-audience': '@saaskit/perfect-audience',
    'pingdom': '@saaskit/pingdom',
    'piwik': '@saaskit/piwik',
    'preact': '@saaskit/preact',
    'qualaroo': '@saaskit/qualaroo',
    'quantcast': '@saaskit/quantcast',
    'rollbar': '@saaskit/rollbar',
    'route': '@saaskit/route',
    'saasquatch': '@saaskit/saasquatch',
    'satismeter': '@saaskit/satismeter',
    'segmentio': '@saaskit/segmentio',
    'sentry': '@saaskit/sentry',
    'snapengage': '@saaskit/snapengage',
    'spinnakr': '@saaskit/spinnakr',
    'supporthero': '@saaskit/supporthero',
    'taplytics': '@saaskit/taplytics',
    'tapstream': '@saaskit/tapstream',
    'trakio': '@saaskit/trakio',
    'twitter-ads': '@saaskit/twitter-ads',
    'userlike': '@saaskit/userlike',
    'uservoice': '@saaskit/uservoice',
    'vero': '@saaskit/vero',
    'visual-website-optimizer': '@saaskit/visual-website-optimizer',
    'webengage': '@saaskit/webengage',
    'woopra': '@saaskit/woopra',
    'wootric': '@saaskit/wootric',
    'yandex-metrica': '@saaskit/yandex-metrica'
  }

function package(name) {
    return {
        "name": `@saaskit/adroll`,
        "version": "0.2.0",
        "private": false,
        "description": `SaaSkit integration with ${name}`,
        "repository": `saas-studio/saaskit/integrations/${name}`,
        "homepage": `https://saaskit.js.org/integrations/${name}`,
        "author": "SaaS.Dev",
        "license": "MIT",
        "main": "index.js",
        "dependencies": {
          "saaskit": "latest"
        }
    }
}

for (integration in integrations) {
    console.log(integration)
    jsonfile.writeFileSync(`../integrations/${integration}/package.json`, package(integration))
}
  