/**
 * Auth Provider Generator
 *
 * Generates a react-admin AuthProvider implementation customized
 * based on the schema's User resource if present.
 *
 * @see saaskit-qnr
 */

import type { SaaSSchema, Resource, Field } from '@saaskit/schema'
import type { GeneratedComponent } from '../types'

// ============================================================================
// Types
// ============================================================================

export interface AuthProviderOptions {
  /** Storage key for auth data */
  storageKey?: string
  /** Whether to include role-based permissions */
  includePermissions?: boolean
  /** Default permissions when none found */
  defaultPermissions?: string[]
}

// ============================================================================
// Helpers
// ============================================================================

/**
 * Find the User resource in a schema
 */
function findUserResource(schema: SaaSSchema): Resource | undefined {
  return schema.resources.find(
    (r) => r.name.toLowerCase() === 'user' || r.name.toLowerCase() === 'account'
  )
}

/**
 * Check if a User resource has a specific field
 */
function hasField(resource: Resource, fieldName: string): boolean {
  return resource.fields.some((f) => f.name.toLowerCase() === fieldName.toLowerCase())
}

/**
 * Get identity fields from User resource
 */
function getIdentityFields(resource: Resource): { id: string; fullName: string | null; avatar: string | null } {
  const idField = resource.fields.find(
    (f) => f.name === 'id' || f.annotations?.primaryKey
  )?.name || 'id'

  const nameField = resource.fields.find(
    (f) => ['name', 'fullName', 'displayName', 'username'].includes(f.name)
  )?.name || null

  const avatarField = resource.fields.find(
    (f) => ['avatar', 'avatarUrl', 'profileImage', 'image'].includes(f.name)
  )?.name || null

  return { id: idField, fullName: nameField, avatar: avatarField }
}

/**
 * Check if User resource has role/permissions fields
 */
function getPermissionField(resource: Resource): string | null {
  const permField = resource.fields.find(
    (f) => ['role', 'roles', 'permissions', 'permission'].includes(f.name.toLowerCase())
  )
  return permField?.name || null
}

/**
 * Check if User has email field for login
 */
function getEmailField(resource: Resource): string | null {
  const emailField = resource.fields.find(
    (f) => f.type === 'email' || f.name.toLowerCase() === 'email'
  )
  return emailField?.name || null
}

// ============================================================================
// Generator
// ============================================================================

/**
 * Generate an authProvider implementation for react-admin
 *
 * Customizes the auth provider based on the User resource in the schema:
 * - Uses email field for login if present
 * - Extracts identity fields (name, avatar) for getIdentity
 * - Includes role/permission handling if User has role fields
 *
 * @param schema - The SaaS schema
 * @param options - Optional configuration
 * @returns Generated authProvider component
 */
export function generateAuthProvider(
  schema: SaaSSchema,
  options: AuthProviderOptions = {}
): GeneratedComponent {
  const { storageKey = 'auth', includePermissions = true, defaultPermissions = [] } = options

  const userResource = findUserResource(schema)

  // Get field info from User resource if present
  const emailField = userResource ? getEmailField(userResource) : null
  const identityFields = userResource ? getIdentityFields(userResource) : { id: 'id', fullName: null, avatar: null }
  const permissionField = userResource && includePermissions ? getPermissionField(userResource) : null

  // Build the login parameters based on User resource
  const loginParams = emailField
    ? `{ ${emailField}, password }`
    : '{ username, password }'

  // Build identity return based on available fields
  const identityReturn = buildIdentityReturn(identityFields)

  // Build permissions return
  const permissionsReturn = permissionField
    ? `const { ${permissionField} } = JSON.parse(auth)
      return ${permissionField} || ${JSON.stringify(defaultPermissions)}`
    : `return ${JSON.stringify(defaultPermissions)}`

  const code = `import type { AuthProvider } from 'react-admin'

/**
 * Auth Provider for ${schema.metadata.name}
 * ${userResource ? `Customized for ${userResource.name} resource` : 'Basic stub implementation'}
 *
 * @generated by @saaskit/shadmin-codegen
 */
export const authProvider: AuthProvider = {
  login: async (${loginParams}) => {
    // TODO: Implement actual authentication logic
    // This should call your auth API endpoint
    const identifier = ${emailField ? emailField : 'username'}
    localStorage.setItem('${storageKey}', JSON.stringify({
      ${identityFields.id}: identifier,
      ${emailField ? `${emailField}: ${emailField}` : 'username: username'}${identityFields.fullName ? `,\n      ${identityFields.fullName}: identifier` : ''}${permissionField ? `,\n      ${permissionField}: []` : ''}
    }))
    return Promise.resolve()
  },

  logout: async () => {
    localStorage.removeItem('${storageKey}')
    return Promise.resolve()
  },

  checkAuth: async () => {
    const auth = localStorage.getItem('${storageKey}')
    if (auth) {
      return Promise.resolve()
    }
    return Promise.reject()
  },

  checkError: async (error) => {
    const status = error?.status || error?.response?.status
    if (status === 401 || status === 403) {
      localStorage.removeItem('${storageKey}')
      return Promise.reject()
    }
    return Promise.resolve()
  },

  getIdentity: async () => {
    const auth = localStorage.getItem('${storageKey}')
    if (auth) {
      ${identityReturn}
    }
    return Promise.reject()
  },

  getPermissions: async () => {
    const auth = localStorage.getItem('${storageKey}')
    if (auth) {
      ${permissionsReturn}
    }
    return ${JSON.stringify(defaultPermissions)}
  },
}
`

  return {
    name: 'authProvider',
    code,
    imports: ['AuthProvider'],
    filePath: 'authProvider.ts',
  }
}

/**
 * Build the identity return statement based on available fields
 */
function buildIdentityReturn(fields: { id: string; fullName: string | null; avatar: string | null }): string {
  const parts = [`id: parsed.${fields.id}`]

  if (fields.fullName) {
    parts.push(`fullName: parsed.${fields.fullName}`)
  } else {
    parts.push(`fullName: parsed.${fields.id}`)
  }

  if (fields.avatar) {
    parts.push(`avatar: parsed.${fields.avatar}`)
  }

  return `const parsed = JSON.parse(auth)
      return { ${parts.join(', ')} }`
}
