/**
 * Create Component Generator
 *
 * @see saaskit-74v, saaskit-oom
 */

import type { Resource, Field } from '@saaskit/schema'
import type { GeneratedComponent } from '../types'
import { mapFieldType } from '../field-mapper'

const AUTO_GENERATED_TYPES = ['uuid', 'datetime']

function isAutoGenerated(field: Field): boolean {
  if (AUTO_GENERATED_TYPES.includes(field.type)) return true
  if (field.annotations?.primaryKey) return true
  if (field.annotations?.autoGenerated) return true
  return false
}

function getInputProps(field: Field): Record<string, unknown> {
  const props: Record<string, unknown> = { source: field.name }

  if (field.annotations?.description) {
    props.helperText = field.annotations.description
  }
  if (field.required) {
    props.required = true
  }
  if (field.type === 'enum') {
    const choices = (field.annotations?.enumValues || []).map((v: string) => ({ id: v, name: v }))
    props.choices = choices
  }

  return props
}

function formatProps(props: Record<string, unknown>): string {
  return Object.entries(props)
    .map(([key, value]) => {
      if (typeof value === 'string') return `${key}="${value}"`
      if (typeof value === 'boolean' && value) return key
      return `${key}={${JSON.stringify(value)}}`
    })
    .join(' ')
}

export function generateCreate(resource: Resource): GeneratedComponent {
  const componentName = `${resource.name}Create`
  const imports = new Set<string>(['Create', 'SimpleForm'])

  const inputs: string[] = []
  for (const field of resource.fields) {
    // Skip auto-generated fields in create forms
    if (isAutoGenerated(field)) continue

    const mapping = mapFieldType(field, { isCreate: true })
    const component = mapping.inputComponent
    const props = getInputProps(field)
    imports.add(component)
    inputs.push(`      <${component} ${formatProps(props)} />`)
  }

  const code = `export const ${componentName} = () => (
  <Create>
    <SimpleForm>
${inputs.join('\n')}
    </SimpleForm>
  </Create>
)`

  return {
    name: componentName,
    code,
    imports: Array.from(imports),
    filePath: `${resource.name}/${componentName}.tsx`,
  }
}
