# Blog Schema
# Demonstrates many-to-many relationships and content management patterns
#
# Resources:
#   - posts: Blog posts with rich content and publication workflow
#   - authors: Content creators with profile information
#   - tags: Categorization labels for posts
#   - post_tags: Junction table for many-to-many posts <-> tags relationship
#   - comments: User-submitted comments on posts

app:
  name: blog
  displayName: Blog
  version: "1.0.0"
  description: A full-featured blog platform demonstrating many-to-many relationships and content management workflows
  baseUrl: http://localhost:3000
  targets:
    cli: true
    api: true
    sdk: true
    mcp: true

resources:
  # Authors - Content creators
  - name: Author
    pluralName: Authors
    path: /authors
    displayName: Author
    description: Blog content authors and their profiles
    icon: user
    fields:
      - name: id
        type: text
        modifiers:
          auto: true
          primary: true
          unique: true
        description: Unique author identifier

      - name: name
        type: text
        modifiers:
          required: true
        label: Full Name
        description: Author's display name
        placeholder: "John Doe"

      - name: email
        type: email
        modifiers:
          required: true
          unique: true
        label: Email Address
        description: Author's email address (unique)
        placeholder: "john@example.com"

      - name: bio
        type: textarea
        modifiers:
          optional: true
        label: Biography
        description: Short biography or description
        placeholder: "A few sentences about the author..."

      - name: avatar_url
        type: url
        modifiers:
          optional: true
        label: Avatar URL
        description: URL to author's profile image
        placeholder: "https://example.com/avatar.jpg"

  # Posts - Blog content
  - name: Post
    pluralName: Posts
    path: /posts
    displayName: Post
    description: Blog posts with content, publication status, and author relationships
    icon: file-text
    fields:
      - name: id
        type: text
        modifiers:
          auto: true
          primary: true
          unique: true
        description: Unique post identifier

      - name: title
        type: text
        modifiers:
          required: true
        label: Title
        description: Post title
        placeholder: "My Amazing Blog Post"
        min: 1
        max: 200

      - name: slug
        type: text
        modifiers:
          required: true
          unique: true
        label: URL Slug
        description: URL-friendly identifier (must be unique)
        placeholder: "my-amazing-blog-post"
        pattern: "^[a-z0-9]+(?:-[a-z0-9]+)*$"

      - name: content
        type: textarea
        modifiers:
          required: true
        label: Content
        description: Full post content (supports markdown)
        placeholder: "Write your post content here..."

      - name: excerpt
        type: textarea
        modifiers:
          optional: true
        label: Excerpt
        description: Short summary for previews and SEO
        placeholder: "A brief summary of the post..."
        max: 500

      - name: status
        type: select
        modifiers:
          required: true
        label: Status
        description: Publication status
        values:
          - draft
          - published
          - archived
        default: draft

      - name: published_at
        type: date
        modifiers:
          optional: true
        label: Published Date
        description: When the post was/will be published

      - name: author_id
        type: relation
        modifiers:
          required: true
        target: Author
        label: Author
        description: The author who wrote this post

      - name: created_at
        type: date
        modifiers:
          auto: true
        label: Created
        description: When the post was created

      - name: updated_at
        type: date
        modifiers:
          auto: true
        label: Updated
        description: When the post was last modified

  # Tags - Categorization
  - name: Tag
    pluralName: Tags
    path: /tags
    displayName: Tag
    description: Labels for categorizing and organizing posts
    icon: tag
    fields:
      - name: id
        type: text
        modifiers:
          auto: true
          primary: true
          unique: true
        description: Unique tag identifier

      - name: name
        type: text
        modifiers:
          required: true
          unique: true
        label: Name
        description: Tag display name
        placeholder: "Technology"
        min: 1
        max: 50

      - name: slug
        type: text
        modifiers:
          required: true
          unique: true
        label: URL Slug
        description: URL-friendly identifier
        placeholder: "technology"
        pattern: "^[a-z0-9]+(?:-[a-z0-9]+)*$"

      - name: color
        type: text
        modifiers:
          optional: true
        label: Color
        description: Hex color code for UI display
        placeholder: "#3b82f6"
        pattern: "^#[0-9a-fA-F]{6}$"

  # Post Tags - Junction table for many-to-many
  - name: PostTag
    pluralName: PostTags
    path: /post-tags
    displayName: Post Tag
    description: Junction table linking posts to tags (many-to-many relationship)
    icon: link
    fields:
      - name: id
        type: text
        modifiers:
          auto: true
          primary: true
          unique: true
        description: Unique association identifier

      - name: post_id
        type: relation
        modifiers:
          required: true
        target: Post
        label: Post
        description: The post being tagged

      - name: tag_id
        type: relation
        modifiers:
          required: true
        target: Tag
        label: Tag
        description: The tag applied to the post

  # Comments - User feedback
  - name: Comment
    pluralName: Comments
    path: /comments
    displayName: Comment
    description: User-submitted comments on blog posts
    icon: message-square
    fields:
      - name: id
        type: text
        modifiers:
          auto: true
          primary: true
          unique: true
        description: Unique comment identifier

      - name: post_id
        type: relation
        modifiers:
          required: true
        target: Post
        label: Post
        description: The post this comment belongs to

      - name: author_name
        type: text
        modifiers:
          required: true
        label: Author Name
        description: Name of the commenter
        placeholder: "Jane Reader"
        min: 1
        max: 100

      - name: author_email
        type: email
        modifiers:
          required: true
        label: Author Email
        description: Email of the commenter (not displayed publicly)
        placeholder: "jane@example.com"

      - name: content
        type: textarea
        modifiers:
          required: true
        label: Comment
        description: The comment content
        placeholder: "Great post! I learned a lot..."
        min: 1
        max: 5000

      - name: approved
        type: boolean
        modifiers:
          required: true
        label: Approved
        description: Whether the comment is approved for display
        default: false

      - name: created_at
        type: date
        modifiers:
          auto: true
        label: Created
        description: When the comment was submitted

# Relationships Summary:
# - Post belongs to Author (author_id -> Author.id)
# - Post has many Tags through PostTags (many-to-many)
# - Tag has many Posts through PostTags (many-to-many)
# - Comment belongs to Post (post_id -> Post.id)
