# CRM Schema for SaaSkit
# Demonstrates complex relationships between entities
#
# This schema defines a complete Customer Relationship Management system with:
# - Companies (organizations/accounts)
# - Contacts (people at companies)
# - Deals (sales opportunities)
# - Activities (interactions and touchpoints)

metadata:
  name: crm
  version: "1.0.0"
  description: "Customer Relationship Management - Track companies, contacts, deals, and activities"

resources:
  # ==========================================================================
  # Companies - Organizations/Accounts
  # ==========================================================================
  - name: Company
    pluralName: Companies
    description: "Organizations and business accounts"
    timestamps:
      createdAt: true
      updatedAt: true
    fields:
      - name: id
        type: uuid
        required: true
        annotations:
          primaryKey: true
      - name: name
        type: string
        required: true
        description: "Company name"
        annotations:
          searchable: true
          indexed: true
      - name: website
        type: url
        required: false
        description: "Company website URL"
      - name: industry
        type: string
        required: false
        description: "Industry sector (e.g., Technology, Healthcare, Finance)"
        annotations:
          searchable: true
      - name: size
        type: enum
        required: false
        description: "Company size category"
        annotations:
          enumValues:
            - small      # 1-50 employees
            - medium     # 51-200 employees
            - enterprise # 200+ employees
      - name: address
        type: string
        required: false
        description: "Company headquarters address"
      - name: phone
        type: string
        required: false
        description: "Main company phone number"
      - name: notes
        type: string
        required: false
        description: "Internal notes about the company"
    relations: []
    views:
      - name: list
        type: table
        default: true
        columns:
          - field: name
            sortable: true
          - field: industry
            filterable: true
          - field: size
            filterable: true
          - field: website
        pageSize: 25

  # ==========================================================================
  # Contacts - People at Companies
  # ==========================================================================
  - name: Contact
    pluralName: Contacts
    description: "Individual contacts and leads"
    timestamps:
      createdAt: true
      updatedAt: true
    fields:
      - name: id
        type: uuid
        required: true
        annotations:
          primaryKey: true
      - name: name
        type: string
        required: true
        description: "Full name of the contact"
        annotations:
          searchable: true
          indexed: true
      - name: email
        type: email
        required: true
        description: "Primary email address"
        annotations:
          unique: true
          indexed: true
      - name: phone
        type: string
        required: false
        description: "Phone number"
      - name: title
        type: string
        required: false
        description: "Job title"
      - name: status
        type: enum
        required: true
        default: "lead"
        description: "Contact lifecycle stage"
        annotations:
          enumValues:
            - lead       # New lead, not yet qualified
            - prospect   # Qualified, actively being pursued
            - customer   # Has purchased/signed
            - churned    # Former customer
      - name: notes
        type: string
        required: false
        description: "Internal notes about the contact"
    relations:
      - name: company
        to: Company
        cardinality: one
        foreignKey: companyId
        required: false
        inverse: contacts
        onDelete: setNull
    views:
      - name: list
        type: table
        default: true
        columns:
          - field: name
            sortable: true
          - field: email
          - field: company
          - field: status
            filterable: true
          - field: createdAt
            sortable: true
        defaultSort:
          field: createdAt
          direction: desc
        pageSize: 25
      - name: kanban
        type: kanban
        description: "Contacts grouped by status"
        groupBy: status

  # ==========================================================================
  # Deals - Sales Opportunities
  # ==========================================================================
  - name: Deal
    pluralName: Deals
    description: "Sales opportunities and pipeline"
    timestamps:
      createdAt: true
      updatedAt: true
    fields:
      - name: id
        type: uuid
        required: true
        annotations:
          primaryKey: true
      - name: title
        type: string
        required: true
        description: "Deal title/name"
        annotations:
          searchable: true
          indexed: true
      - name: value
        type: number
        required: false
        description: "Deal value in dollars"
        annotations:
          min: 0
      - name: currency
        type: string
        required: false
        default: "USD"
        description: "Currency code (e.g., USD, EUR, GBP)"
      - name: stage
        type: enum
        required: true
        default: "discovery"
        description: "Current stage in the sales pipeline"
        annotations:
          enumValues:
            - discovery    # Initial discovery phase
            - proposal     # Proposal sent
            - negotiation  # In negotiation
            - won          # Deal closed successfully
            - lost         # Deal lost
      - name: probability
        type: number
        required: false
        description: "Win probability percentage (0-100)"
        annotations:
          min: 0
          max: 100
      - name: expectedClose
        type: date
        required: false
        description: "Expected close date"
      - name: closedAt
        type: datetime
        required: false
        description: "Actual close date (when won or lost)"
      - name: lostReason
        type: string
        required: false
        description: "Reason for losing the deal (if applicable)"
      - name: notes
        type: string
        required: false
        description: "Internal notes about the deal"
    relations:
      - name: contact
        to: Contact
        cardinality: one
        foreignKey: contactId
        required: true
        inverse: deals
        onDelete: restrict
      - name: company
        to: Company
        cardinality: one
        foreignKey: companyId
        required: false
        inverse: deals
        onDelete: setNull
    views:
      - name: list
        type: table
        default: true
        columns:
          - field: title
            sortable: true
          - field: value
            sortable: true
          - field: stage
            filterable: true
          - field: contact
          - field: expectedClose
            sortable: true
        defaultSort:
          field: value
          direction: desc
        pageSize: 25
      - name: pipeline
        type: kanban
        description: "Deal pipeline board"
        groupBy: stage
      - name: calendar
        type: calendar
        description: "Deals by expected close date"
        dateField: expectedClose

  # ==========================================================================
  # Activities - Interactions and Touchpoints
  # ==========================================================================
  - name: Activity
    pluralName: Activities
    description: "Logged interactions: calls, emails, meetings, and notes"
    timestamps:
      createdAt: true
      updatedAt: true
    fields:
      - name: id
        type: uuid
        required: true
        annotations:
          primaryKey: true
      - name: type
        type: enum
        required: true
        description: "Type of activity"
        annotations:
          enumValues:
            - call     # Phone call
            - email    # Email sent/received
            - meeting  # In-person or virtual meeting
            - note     # General note or update
      - name: subject
        type: string
        required: false
        description: "Activity subject/title"
        annotations:
          searchable: true
      - name: notes
        type: string
        required: false
        description: "Detailed notes about the activity"
        annotations:
          searchable: true
      - name: date
        type: datetime
        required: true
        description: "When the activity occurred"
        annotations:
          indexed: true
      - name: duration
        type: number
        required: false
        description: "Duration in minutes (for calls/meetings)"
        annotations:
          min: 0
      - name: outcome
        type: string
        required: false
        description: "Outcome or result of the activity"
    relations:
      - name: contact
        to: Contact
        cardinality: one
        foreignKey: contactId
        required: true
        inverse: activities
        onDelete: cascade
      - name: deal
        to: Deal
        cardinality: one
        foreignKey: dealId
        required: false
        inverse: activities
        onDelete: setNull
    views:
      - name: list
        type: table
        default: true
        columns:
          - field: type
            filterable: true
          - field: subject
          - field: contact
          - field: deal
          - field: date
            sortable: true
        defaultSort:
          field: date
          direction: desc
        pageSize: 50
      - name: timeline
        type: list
        description: "Activity timeline view"
        defaultSort:
          field: date
          direction: desc
      - name: calendar
        type: calendar
        description: "Activities on calendar"
        dateField: date

# ==========================================================================
# Workflows
# ==========================================================================
workflows:
  - name: dealPipeline
    resource: Deal
    stateField: stage
    description: "Sales deal progression workflow"
    states:
      - name: discovery
        description: "Initial discovery and qualification"
        initial: true
      - name: proposal
        description: "Proposal sent to prospect"
      - name: negotiation
        description: "Terms being negotiated"
      - name: won
        description: "Deal successfully closed"
        final: true
        onEnter:
          - updateContactToCustomer
      - name: lost
        description: "Deal lost"
        final: true
    transitions:
      - name: sendProposal
        from: discovery
        to: proposal
        trigger: manual
      - name: startNegotiation
        from: proposal
        to: negotiation
        trigger: manual
      - name: winDeal
        from: negotiation
        to: won
        trigger: manual
        actions:
          - setClosedDate
      - name: loseDeal
        from: negotiation
        to: lost
        trigger: manual
        actions:
          - setClosedDate
      - name: reopen
        from: lost
        to: discovery
        trigger: manual

  - name: contactLifecycle
    resource: Contact
    stateField: status
    description: "Contact lifecycle progression"
    states:
      - name: lead
        description: "New lead, not qualified"
        initial: true
      - name: prospect
        description: "Qualified prospect"
      - name: customer
        description: "Active customer"
      - name: churned
        description: "Former customer"
        final: true
    transitions:
      - name: qualify
        from: lead
        to: prospect
        trigger: manual
      - name: convert
        from: prospect
        to: customer
        trigger: manual
      - name: churn
        from: customer
        to: churned
        trigger: manual
      - name: reactivate
        from: churned
        to: customer
        trigger: manual
